- site/components/screens/FortuneBasket.js
Please review these before merging!
> Add more fortune cookies

- games/BeeSeeker/README.md
Adding my teams game idea, beeseeker
> Add BeeSeeker

- games/MeiHuā/README.md
@felixgao-0, @aramshiva, and @taciturnaxolotl
> add MeiHuā

- games/cavemaestro/README.md
> Add CaveMaestro

- games/HiveQuest/README.md
Me and my team decided to change the name of the game
> Changed name of Beeseeker to Hivequest

- games/Rat Pizzaria/README.md
Had a previous attempt that was completely incorrect. This time tried to do it correctly.
> Add Rat Pizzaria project.

- jump_knight/README.md
> Add JUMP KNIGHT project

- games/Astronox/README.md
Added the read me file for Astronox
> Add Astronox

- games/RiftStrike/README.md
the outline of my game-idea "RiftStrike"; a fast-paced (singleplayer) rougelite with RTS mechanics
> Create RiftStrike README.md

- games/template/README.md
My first version of the game and plausible ideas for the game Harmony Chronicles
> Updated README.md with proposed Idea for the Hackclub Juice Contest

- games/Viñedo/README.md
The turn-based "combat" rougelike!
> Add Viñedo 

- games/Fragmented Machine/README.md
This is my submission for my game idea!
> Add "Fragmented Machine"

- games/ShadowsOfMemory/README.md
A game where you explore the hidden tragedy!
> ShadowsOfMemory Game!

- games/EchoesOfTheForest/README.md
Created Readme for our game Echoes of the Forest
> Create README.md for EchoesOfTheForest

- games/Culinary Crossroads/README.md
pull request of my game Culinary Crossroads which is a street food business simulator.
> Add Culinary Crossroads Projects

- games/UntitledVegetableBullethell/README.md
I dont rly have any good name idea yet so, hopefully the current one is fine
> Add "Untitled Vegetable Bullethell"

- games/chronal-drift/README.md
> Add Chronal Drift Project

- games/shadowSprint/README.md
> Add "Shadow-Sprint" Game.

- games/pineValley/READ.md
i Think ive actually done it the right way this time
sorry about all the messing about im not familiar with github :D
> pine Valley

- games/TheEchoOfSilence/README.md
> Created The Echo Of Silence!

- A-theory-of-evolution/readme.md
by Shree Nagandla and Samhith Pola
> A theory of evolution

- games/dungeon-apocalypse/README.md
- games/idle-dungeon-master/README.md
> added my game, dungeon -apocalypse

- games/Zombie Horde/README.md
I added my game to the games folder
> Adding "Zombie Horde" game

- games/TheSilentJourney/README.md
> Add The Silent Journey

- games/Time Tinkerers
My idea for the game -Time Tinkerers
> Create Time Tinkerers

- games/UniWars/README.md
Katana Zero meets Rockstar's Bully, but with Kanye West’s Graduation aesthetic
> Add UniWars project

- games/bobabliss/README.md
Created initial project README
> Boba Bliss

- games/cathos/README.md
> add cathos game

- games/CavernsEdge/README.md
> Add Cavern's edge project

- games/shake-it!/README.md
> Add Shake It project

- games/DriftMetal/README.md
A fishing metroidvania where you play as a scrapped robot who needs to buy limps to progress.
> Add DriftMetal Project

- games/Mix Smash Realm/README.md
> Add Mix_Smash_Realm Project

- games/Echoes of Elsewhere
Just adding my game idea
- Kishan
> Create Echoes of Elsewhere project

- games/CHAMPIONSHIP/README.md
Which is short for: **Cosmic Heroes Assemble: Mighty Powers Ignite Omega Nemesis Showdown Heroic Infinite Pantheon**
> Add CHAMPIONSHIP

- games/Exploding-Cats/README.md
**Team Members:** Jamie Chopon
**How would you pitch your game in one line?**
It's like Valorant/CSGO meets Tower defense but with little cats
**What is the key mechanic(s) that make it fun?**
[Describe how the mechanic works, why it's fun/important, how it interacts with other mechanics, etc]
The key mechanic is entering a site, and planting the bomb. This going to be fun because you can shoot a bunch of angry robots, and can see the bomb explode a big robot factory. 
**How does the game actually play? (Core Game Loop)**
Main premise: 
Players have a roadtrip map for robot factories they have to explode, with the final location being the final ultron boss.
To explode the factories they have to enter the site and plant the bomb.
Once the bomb is planted, they have to protect it until the …
> add Exploding-Cats project

- games/rampant_routing/README.md
A game about routing PCBs, with a twist…
> Add Rampant Routing

- games/HotSauceAdventure/README.md
Adds a submission for the Hot Sauce Adventure project
> Add Hot Sauce Adventure project

- games/Once-Upon-a-Pizza/README.md
**Team Members:** Jiyeon Choo, Sol Jin
**How would you pitch your game in one line?**
"It's like Good Pizza, Great Pizza meets memory game but in a fairytale world."
**What is the key mechanic(s) that make it fun?**
Varying time limits for each order, taking notes of orders through icons (typed via 0-9), and cooking the pizza by dragging and dropping the ingredients.
Points based on the accuracy of the served pizza and time spent cooking decide the amount paid and whether the customers will leave special tips or not. 
**How does the game actually play? (Core Game Loop)**
The players receive orders in the form of shapes that mean certain ingredients for the pizza. 
They have to go through trial and error to guess the ingredients correctly. They also lose coins to refill the ingredients. 
A …
> add Once Upon a Pizza

- games/theSiderooms/README.md
Through this I'll be adding "The Siderooms" and the game idea to Juice's games list.
> Adding "The Siderooms"

- games/vrParty/README.md
**VrParty** is a multiplayer VR game where up to 6 players wearing Oculus Quest 2 headsets can enjoy a variety of fun, fast-paced minigames together in the same room. 
With challenges ranging from reflex-based games to team puzzles, players compete to earn the highest score across multiple rounds. 
The game is designed to keep players engaged with diverse gameplay, dynamic competition, and the unique social interaction of local VR multiplayer. Perfect for quick, energetic sessions with friends!
> Add VRParty project

- games/CityBreakout/README.md
City Breakout combines fast-paced and evolving gameplay, parkour abilities, engaging levels, and a variety of game modes for single-player and multiplayer. It is a thrilling challenge, rewarding in its progress, and keeps players engaged with new abilities.
> Add Citybreakout game

- games/Melody Glyphs/README.md
a new game!!!!!!!!!!!!!!!!
Melody Glyphs
> New game --- Melody Glyphs

- games/Cricket Cosmos/README.md
Cricket but with Physics-based Chaos!
> Add Cricket Cosmos

- games/Epoch/README.md
oops i copy pasted and then i forgot to change the title
> fix Epoch readme

- games/Hellevator/README.md
> Add hellevator

- games/FastFlowFishing/README.md
> Add Fast Flow Fishing!

- games/ABYSS/README.md
- games/echo/README.md
The initial PR for a game collab with @greatgoatman33
> ABYSS: A game of echolocation and monsters

- games/FINALDESTINATION/README.md
> Addded my game! FINALDESTINATION

- games/unreal-dungeons/README.md
by Anvid (Andrés) & Azhvery (Helman)
> Unreal Dungeons

- games/finalfast/README.md
> chore: FinalFest - Created the README with the infos about the game

- games/Melanotaenia/README.md
Game Melanotaenia for juice Game Jam.
> add Melanotaenia

- games/glitch-out/README.md
> Add 'Glitch Out' project

- games/Swo-No-Con/README.md
> Swo-No-Con

- games/cradle-catchers/README.md
> Cradle Catchers

- games/blahajDoomsday/README.md
- games/sharkDoomsday/README.md
our game idea for team juicy blahaj!
> Shark Doomsday

- games/Flowlement/README.md
Add the juice project of @ag11901
> Create Flowlement project

- games/你喜欢火车吗？ (do you like trains)
> Create 你喜欢火车吗？ (do you like trains)

- games/starfire/README.md
> added starfire

- games/Easy-Peasy/README.md
> Add Easy Peasy

- games/conveyance/readme.md
God I hope I actually finish a project for once
> Conveyance

- games/Echoes of the Past/README.md
Added my game "Solace" - Raghav Kumar
> Create README.md for Solace

- games/Maya
Team Members: [Kareem Ibrahim, Karolina Wisniewski]
How would you pitch your game in one line?
A fast-paced platform game where a pigeon falls out of a tree and has to avoid obstacles, fight
bosses, and finally, build a rocket in order to find its place in the skies
What is the key mechanic(s) that make it fun? 
The variety of levels with unique hazards, bosses, and collectibles. Additionally, being able to
play this game as a small pigeon navigating a big world provides the user with an atypical, 
interesting experience with new challenges to face.
How does the game actually play? (Core Game Loop) 
Players have to reach the end of a level, having avoided all of the obstacles/hazards and
defeated any bosses, to gain another piece of the rocket. The storyline progresses through
each level, …
> add Maya game

- games/allWallsLeadToZombies/README.md
> add All Roads Lead to Zombies game

- games/MirrorSwap/README.md
Added my Mirrorswap readme file.
> Add Mirrorswap project

- games/Ascent/README.md
> Create Ascent game idea

- BuryTheLight/README.md
> Adding game readme

- games/Blended/README.md
- site/pages/api/get-omg-moments.js
Sorry for being late, I made the pr on my own repo instead of the main repo :(.
The link on the juice website for the PR achievement links to the original PR made before the deadline.
Other than that, this PR is the exact same as the other one.
> Add Blended (I made a pull request on my own repo :( )

- games/Hack-Slash-Stab/README.md
> Create README.md for Hack-Slash-Stab!

- games/shadowscaper/README.md
**Team Members:** K.K. (just me :D)
**How would you pitch your game in one line?**
[example format: "It's like [Game X] meets [Game Y] but with [Unique Element Z]" (doesn't have to follow this format)] 
it's olaf's situation with wanting to remain frozen in the summertime except you're a shadow navigating a world of light
**What is the key mechanic(s) that make it fun?** 
[Describe how the mechanic works, why it's fun/important, how it interacts with other mechanics, etc] 
it's single player, so you can lose yourself in another world where you're trying to constantly avoid light sources and manipulate objects to cast darkness and cast new shadows to keep moving.
it has a basic 2D layout, and it's a platformer game where you'll have to effectively time your movements and use what you have …
> add shadowscaper game

- games/Deauthenticated/README.md
> Created README.md for Deauthenticated

- games/template/README.md
Fixed a badly merged PR that screwed up the project template.
The game that was supposed to merge has been merged in a different PR here: [https://github.com/hackclub/juice/pull/192](https://github.com/hackclub/juice/pull/192)
> Fix game template README.md

- games/Shattered Echoes.txt/README.md
**Game Name**: *Shattered Echoes*
**Team Members**: Utkarsh Nande
**One-Line Pitch**: "It's like Hyper Light Drifter meets Dead Cells, but you weaponize light and shadows to reshape the environment and outsmart evolving enemies."
**Key Mechanics**:  
- *Light/Shadow Manipulation*: Toggle between light (burn enemies, melt obstacles) and shadow (cloak, set traps).  
- *Echo System*: Death resets the run, but environmental changes persist, creating shortcuts for future runs.  
- *Symbiotic Orb*: Attack and cloak modes swapped mid-combat for hybrid effects.  
**Core Game Mechanics**:  
Players use light to burn enemies and shadow to set traps, toggling between them for tactical advantage. Light attracts stronger enemies, while shadow limits visibility, creating a dynamic risk-reward system. …
> add Shattered Echoes

- games/BitSkiier/README.md
Added our game BitSkiier for our juice project.
> Added our game BitSkiier!

- games/Slumbering Metro/README.md
Hi! This is my first time ever doing a pull request, please DM me on Slack if I did something wrong.
> Add Slumbering Metro

- games/MELTDOWN/README.md
> Add MELTDOWN Game

- games/Runic Oblivion/README.md
- games/your-game-name/README.md
2D game where you fight with magic.
Will be filled out!
> Game "Runic Oblivion"

- games/HiveQuest/README.md
> Remove kas from team (he dropped out)

- site/components/screens/MainView.js
- site/components/screens/WutIsRelayWindow.js
amended dates for the relay window as well
> fixed dates (properly this time)

- site/components/screens/MainView.js
- site/components/screens/MainViewZero.js
- site/components/screens/ZeroWindow.js
Also move tamagatchi to a sensible position
> Update Juice Zero

- games/DeliveryDash
**Team Members:** [@atremis9703]
**How would you pitch your game in one line?**
[You are a delivery driver trying to deliver food within a time limit]
**What is the key mechanic(s) that make it fun?**
[You have to navigate a city, while delivering food and picking up more orders]
**How does the game actually play? (Core Game Loop)**
[pick up orders from different restaurants, deliver the food to customers' houses]
**How will you keep players engaged for 30 minutes? What's the general scope of your game (will change as you go)?**
[the difficulty increases as u complete more days, you can earn rewards like hiring extra help or faster vehicles]
---
*Remember: Focus on gameplay mechanics and player experience. Save the details about story, art style, sound design, UI flowcharts, marketing …
> add DeliveryDash

- site/components/screens/MenuWindow.js
> fixed x-overflow in moments app by changing number of grid columns

- games/martucci/README.md
> Create README.md(add a dante game)

- games/DragonKnight/README.md
Announcing the Game DragonKnight!
> Add DragonKnight game to Juice!!

- games/Vigilantes of the Cosmos
> Create Vigilantes of the Cosmos

- site/pages/api/deck/add.js
- site/pages/api/register.js
- site/pages/api/submit-address.js
- site/pages/api/submit-pr.js
- site/pages/api/user.js
Removed the need of the `AIRTABLE_TABLE_NAME` environment variable as it was not changing anyway
> replace all of `AIRTABLE_TABLE_NAME`

- express-server/src/controllers/videoController.js
> Revert "Fix bug :pf:"

- games/Limerence/README.md
> Add Limerence

- site/components/screens/MainView.js
- site/components/screens/WutIsBubbleathonWindow.js
juiceathon by neha and tongyu! hopefully everything works
> add bubbleathon

- games/Chrono:\\link/README.md
Hello! We would love to add our game, Chrono:\\Link!
> Add Chrono:\\Link Game!

- game/Nine Lives Kitchen/README.md
> Add Nine Lives Kitchen

- site/pages/exhibit.js
New components and features:
* Added `GameCarousel` component to automatically cycle through a list of games every 3 seconds.
* Added `PostcardsSection`, `FlightMapSection`, `VideoShowcaseSection`, `FinalCTASection`, and `Footer` components to display additional content on the exhibit page.
* Updated translations to include new text for the added sections in both English and Mandarin. [[1]](diffhunk://#diff-ad1cf73a1f51855dc6a5f1025491ec2ba798f3636faaeeb7d37b1a04c5516d62L160-R262) [[2]](diffhunk://#diff-ad1cf73a1f51855dc6a5f1025491ec2ba798f3636faaeeb7d37b1a04c5516d62L180-R290)
> Update exhibit.js (Added main Page content (but no real content))

- games/Ironshift/README.md
I renamed my game from `Minetorio` to `Ironshift`.
> Renamed my game

- games/Tetrookie/README.md
> add Tetrookie

- games/undead-courier/README.md
Updated my original idea to what i've developed now
> Updated game desc
